apiVersion: v1
kind: Service
metadata:
  name: calculators
  namespace: live
spec:
  selector:
    run: calculators
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: calculators
  namespace: live
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/tags: App=calculators,Namespace=live
    alb.ingress.kubernetes.io/healthcheck-path: /child-benefit-tax-calculator/main
spec:
  rules:
    - host: calculators.live.in-cluster.govuk-k8s.test
      http:
        paths:
          - path: /*
            backend:
              serviceName: calculators
              servicePort: 3000
