apiVersion: v1
kind: Service
metadata:
  name: calculators
spec:
  selector:
    run: calculators
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31001
  type: NodePort
