apiVersion: v1
kind: Service
metadata:
  name: calendars
spec:
  selector:
    run: calendars
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31002
  type: NodePort
