apiVersion: v1
kind: Service
metadata:
  name: collections
spec:
  selector:
    run: collections
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31003
  type: NodePort
