apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    run: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31007
  type: NodePort
