apiVersion: v1
kind: Service
metadata:
  name: info-frontend
spec:
  selector:
    run: info-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31009
  type: NodePort
