apiVersion: v1
kind: Service
metadata:
  name: service-manual-frontend
spec:
  selector:
    run: service-manual-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31013
  type: NodePort
