apiVersion: v1
kind: Service
metadata:
  name: smart-answers
spec:
  selector:
    run: smart-answers
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31012
  type: NodePort
