FROM registry.govuk-k8s.test:5000/govuk-base:latest

COPY --chown=govuk . /app

WORKDIR /app

RUN rbenv install -s && \
    gem install --conservative --no-document bundler -v $(grep -A1 "BUNDLED WITH" Gemfile.lock | tail -1) && \
    bundle

RUN \
    bundle exec rake assets:precompile && \
    bundle exec rake yarn:install && \
    echo 'ENV["K8S_HOSTNAMES"].split(",").each { |host| Rails.application.config.hosts << host }' > config/initializers/k8s.rb

CMD bin/rails s --restart
